policy:
  approval:
    - pr is not too big

  approval_rules:
    - name: pr is not too big
      options:
        allow_contributor: true
        invalidate_on_push: true
      requires:
        count: 1
