policy:
  approval:
    - pr is not too big

  approval_rules:
    - name: pr is not too big
      if:
        modified_lines:
          # additions: "> 100"
          # deletions: "> 100"
          total: "< 10"
      options:
        invalidate_on_push: true
      requires:
        count: 0
